### ISSUE TITLE
Question about when downloading Kinetics dataset, there is an error: Don't know why something went wrong?

### ISSUE THREAD

**Issue by qiuqicao77** [piaxar/kinetics-downloader#1]

**Comment by svakav** [comment]
@qiuqicao77 Hi. Did you manage to find out what was the issue? If not, perhaps you used another downloader?

**Comment by piaxar** [comment]
Hi!

I apologize for not responding to the problem for a long time.

Regarding the issue. Given error is thrown [here](https://github.com/piaxar/kinetics-downloader/blob/fd4e3d8f8f35c3418a3894f86cea177f263585c6/download.py#L66). As you may notice, the catched exception is thrown from pytube library. I didn't work with this code for a long time but when I used to, this error was rare enough to ignore it.

To make this problem less unclear, I commented the error-avoiding code. Now script will print you an error thrown from the library. I hope it will help you to debug the script.
