### ISSUE TITLE
Something went wrong when I set '--num-jobs' over than one.

### ISSUE THREAD

**Issue by LjccjL** [piaxar/kinetics-downloader#2]
Code runs well when the num of jobs is one.
Can't figure out the reason, could you give me some clues?

**Comment by piaxar** [comment]
At first, do you have the latest version of the code? I've made changes throwing error instead of ignoring it. ( #1 )

If it won't help, please share the output of the run and we'll try to figure the problem.

**Comment by LjccjL** [comment]
The code is the latest version, and the ouput is shown as below.
![image](https://user-images.githubusercontent.com/32026152/66793030-22081580-ef2e-11e9-9997-18d0950dea07.png)
![image](https://user-images.githubusercontent.com/32026152/66793208-e15ccc00-ef2e-11e9-9972-b67bb989cdbe.png)

**Comment by LjccjL** [comment]
There may be some unknown errors in joblib.Parallel. Anyway, problem solved. 
![image](https://user-images.githubusercontent.com/32026152/66814487-3c131980-ef69-11e9-84fc-b58c340e253d.png)

**Comment by sheetalojha** [comment]
@LjccjL
I did the changes you mentioned but I am still getting this error. Do you know how to combat this?
'''
(venv2) root@ip-164-33-17-29:/home/ubuntu/sheetal/kinetics-downloader# python download.py kinetics400/train.csv /datasets/ --num-jobs 10
Already downloaded:  ---QUuC4vJs
Processed 1 out of 221712
Already downloaded:  --4-0ihtnBU
Processed 3 out of 221712
Already downloaded:  --3ouPhoy2A
Already downloaded:  --56QUhyDQM
Start downloading:  --6q_33gNew
Start downloading:  --EaS9P7ZdQ
Processed 2 out of 221712
Processed 4 out of 221712
Start downloading:  --IPbe5ZMCI
Already downloaded:  --Ntf6n-j9Q
Processed 8 out of 221712
Already downloaded:  --PyMoD3_eg
Processed 9 out of 221712
Already downloaded:  --TBx-Spzis
Processed 10 out of 221712
Already downloaded:  --UW3CcUqaU
Processed 11 out of 221712
Start downloading:  --VnA3ztuZg
Start downloading:  --_S9IDQPLg
Start downloading:  --bO6XwZ9HI
Start downloading:  --feYHvtteA
Start downloading:  --gx7yb1-x0
Start downloading:  --j-y5SNUhs
Start downloading:  --jD1Yu5ZnQ
Start downloading:  --lrRHlpK68
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'pattern' 
'''
