### ISSUE TITLE
Videos are always unavailable

### ISSUE THREAD

**Issue by misunusc** [piaxar/kinetics-downloader#3]
I follow the ReadMe to install the environment and run the download.py script. 
Unfortunately, nothing is downloaded. 
The program always throw the exception from pytube.exceptions.VideoUnavailable, i.e., Videos are always unavailable. However, videos can be access by directly opening the links (URL_BASE + filename) on chrome web browser. I guess it has something to do with pytube.
Could you help me solve this issue?
I really appreciate if can.
Thanks.

**Comment by misunusc** [comment]
Also, could you please share the kinetics data via GoogleDrive to me?
I really appreciate if can.
Thanks.

**Comment by saliknadeem** [comment]
I was facing a similar issue. In the code, uncomment the lines 65-67 which will throw an exception if a video is unavailable and move on to the next one.

**Comment by misunusc** [comment]
This issue is because that the
